### ISSUE TITLE
Check Swagger auth possibilities

### ISSUE THREAD

**Issue by KonradSzwarc** [CodersCrew/coderscamp#164]

**Comment by nowakprojects** [comment]
For me it's not a problem to authorize in Swagger. 
I don't know how to with GitHub, but with local JWT it should be startightforward. 
 
https://swagger.io/docs/specification/authentication/bearer-authentication/
https://docs.nestjs.com/openapi/introduction

I've added new task to do it: 
https://github.com/CodersCrew/coderscamp/issues/311
