### ISSUE TITLE
Adding information about the format and size of the downloaded file

### ISSUE THREAD

**Issue by wierzbka10** [CodersCrew/coderscamp#210]
This is related to criterion 2.4.4 of the WCAG
![plik do pobrania](https://user-images.githubusercontent.com/46423273/130980747-7ab75bbf-1bcd-4efb-b2a1-165908a56d9a.png)

**Comment by KonradSzwarc** [comment]
Here is no file to download - only a link to Google Drive. I think we can close this issue

**Comment by wierzbka10** [comment]
> 
> 
> Here is no file to download - only a link to Google Drive. I think we can close this issue

Yes, we can close this issue.
