### ISSUE TITLE
[EventRepository] Fix concurrency issues of PrismaEventRepository

### ISSUE THREAD

**Issue by htk4** [CodersCrew/coderscamp#356]
## Problem description

Current implementation of PrismaEventRepository doesn't guarantee aggregate invariants ([streamId, streamVersion]
uniqnues) in concurrent environment.

```js
const currentStreamVersion = await prisma.event.count({ where: { streamId: streamName.streamId } });

if (currentStreamVersion !== expectedStreamVersion) {
  throw new Error(
    `Event stream ${streamName.raw} expected version is: ${expectedStreamVersion}, but current version is: ${currentStreamVersion}`,
  );
}

const databaseEvents = events.map((e, index) => ({
  id: e.id,
  type: e.type,
  streamId: streamName.streamId,
  streamCategory: streamName.streamCategory,
  streamVersion: currentStreamVersion + 1 + index,
  occurredAt: e.occurredAt,
  data: JSON.stringify(e.data),
  metadata: JSON.stringify(e.metadata),
}));

await prisma.event.createMany({ data: databaseEvents });
```

If two or more transactions will run simultaneously `prisma.event.count` then for all of them condition
`currentStreamVersion !== expectedStreamVersion` will be always false and `streamVersion` can be repeated many times for
the same `streamId`.

[LOG](https://github.com/CodersCrew/coderscamp/blob/concurrency-problems/concurrent_transaction.log)

### Sub problem

What's more PrismaEventRepository uses Interactive Transactions which (for now) aren't production ready
([prisma docs](https://www.prisma.io/docs/concepts/components/prisma-client/transactions#concurrent-interactive-transactions-may-timeout), [github issue](https://github.com/prisma/prisma/issues/8707)). This causes unexpected behaviour of prismaService, cascade rollback of transactions and failing tests etc.

## **Solution**

1. Replace Interactive Transactions with
   [The $transaction API](https://www.prisma.io/docs/concepts/components/prisma-client/transactions#the-transaction-api)
2. Introduce new locking table to guarantee uniqueness of [streamId, streamVersion]. Adding uniqueness to existing table
   `Event` [can cause gaps in `globalOrder` values](https://stackoverflow.com/questions/35849944/postgresql-serial-incremented-on-failed-constraint-insert).

```prisma
model EventLock {
  streamId      String
  streamVersion Int

  @@unique([streamId, streamVersion])
}
```

Summon: @nowakprojects

**Comment by nowakprojects** [comment]
Ad. 1 - Is it possible? I don't know if it fully cover interactive transactions use cases. Probably not.

**Comment by htk4** [comment]
Probably it's possible. After all, we only have two 'write' tables. It doesn't covers but if we wanna use prisma transactions, for now we only have this.
