### ISSUE TITLE
Create endpoint for the initial form

### ISSUE THREAD

**Issue by KonradSzwarc** [CodersCrew/coderscamp#67]
**Acceptance criteria:**
- There is an `POST /users/initial-form` endpoint.
- The endpoint takes data structure defined in cooperation with the author of #3.
- Basic data is saved as a part of the User entity. It contains full name, email, city, and sex.
- Rest of the data is saved as a separate entity and connected to the user with one-to-one relation.
- All related data models are placed in the `shared` directory.

**Comment by kacper-cyra** [comment]
Do we first require users to register through GitHub or they first complete the form?

**Comment by KonradSzwarc** [comment]
First, they need to register through GitHub
