### ISSUE TITLE
Create checklist generation endpoint

### ISSUE THREAD

**Issue by KonradSzwarc** [CodersCrew/coderscamp#68]
**Events flow:**
- Endpoint receives a request to generate a new Process.st checklist with the ID of the user requesting it.
- Server uses the provided ID to receive full name of the user.
- A bot is invoked.
- Bot goes to the link specified in `PROCESS_ST_URL` environment variable.
- Bot waits for the webpage to redirect to the address with a generated checklist.
- Bot returns the URL of the generated checklist.
- Returned URL is saved as `checklistUrl` property of the User entity.

**Comment by nowakprojects** [comment]
Process.st has option of creating list with some variables (simplest is checklist_name), so there is no need to change title, just create.

![image](https://user-images.githubusercontent.com/18637116/127736593-e035418a-6fe5-44e3-bd38-6e475b7a4411.png)
